name: Build APK Debug Check Style

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Time
        run: echo time=$(date +'%s') >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 24
      - name: Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-cleanup: always
      - name: Sign
        if: github.repository_owner == 'tgex0'
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [ -n  "$KEYSTORE" ]; then
            echo storePassword="$KEYSTORE_PASSWORD" > keystore.properties
            echo keyAlias="$KEY_ALIAS" >> keystore.properties
            echo keyPassword="$KEY_PASSWORD" >> keystore.properties
            echo storeFile="${{ github.workspace }}/keystore.jks" >> keystore.properties
            echo "$KEYSTORE" | base64 --decode > ${{ github.workspace }}/keystore.jks
          fi
      - name: Build
        run: ./gradlew assembleDebug --no-scan
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: lawnicons-${{ env.time }}
          path: app/build/outputs/apk/app/debug/*.apk
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 24
      - name: Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Spotless
        run: ./gradlew spotlessCheck --no-scan
  final-status:
    needs:
      - build-apk
      - check-style
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Status
        run: |
          if echo '${{ toJSON(needs.*.result) }}' | grep -Eq '(failure|cancelled)'; then
            echo 'Failure' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          echo 'Success' >> $GITHUB_STEP_SUMMARY
