name: Build APK Debug Release

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Time
        run: echo time=$(date +'%s') >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Java
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 24
      - name: Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          build-scan-publish: false
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'
          cache-cleanup: always
      - name: Sign
        if: github.repository_owner == 'stevenspeirs'
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [ -n  "$KEYSTORE" ]; then
            echo storePassword="$KEYSTORE_PASSWORD" > keystore.properties
            echo keyAlias="$KEY_ALIAS" >> keystore.properties
            echo keyPassword="$KEY_PASSWORD" >> keystore.properties
            echo storeFile="${{ github.workspace }}/keystore.jks" >> keystore.properties
            echo "$KEYSTORE" | base64 --decode > ${{ github.workspace }}/keystore.jks
          fi
      - name: Build
        run: ./gradlew assembleDebug assembleRelease --no-scan
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: lawnicons-${{ env.time }}
          path: app/build/outputs/apk/app/*/*.apk
  final-status:
    needs:
      - build-apk
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Status
        run: |
          if echo '${{ toJSON(needs.*.result) }}' | grep -Eq '(failure|cancelled)'; then
            echo 'Failure' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          echo 'Success' >> $GITHUB_STEP_SUMMARY
